# New ports collection makefile for:	Nemacs
# Date created:				14 Nov 2000
# Whom:					TAKAHASHI Kaoru <kaoru@kaisei.org>
#
# $FreeBSD$
#

PORTNAME=	platex-jsclasses
PORTVERSION=	2000.11.22
CATEGORIES=	japanese print
MASTER_SITES=	http://www.matsusaka-u.ac.jp/~okumura/jsclasses/
DISTNAME=	jsclasses
EXTRACT_SUFX=	.lzh

MAINTAINER=	kaoru@kaisei.org

NO_INSTALL=	YES
NO_BUILD=	YES

do-build:

.include <bsd.port.mk>
