# New ports collection makefile for:	DAHDI Tools
# Date created:				2009-12-10
# Whom:					
#
# $FreeBSD$
#

PORTNAME=	dahdi-tools
PORTVERSION=	0.0.361
CATEGORIES=	net
MASTER_SITES=	http://triaez.kaisei.org/~kaoru/asterisk/

MAINTAINER=	kaoru@kaisei.org
COMMENT=	DAHDI Tools (without kernel module)

WRKSRC=                ${WRKDIR}/${DISTNAME}/tools

#post-install:
#	cd ${WRKDIR}/${DISTNAME}/dahdi && ${MAKE} afterinstall

.include <bsd.port.mk>
