# New ports collection makefile for:	p5-Crypt-NULL
# Date created:		2005-08-06
# Whom:			TAKAHASHI Kaoru <kaoru@kaisei.org>
#
# $FreeBSD: ports/security/p5-Crypt-NULL/Makefile,v 1.1 2005/09/15 15:02:39 lth Exp $
#

PORTNAME=	Crypt-NULL
PORTVERSION=	1.02
CATEGORIES=	security perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Crypt
PKGNAMEPREFIX=	p5-

MAINTAINER=	kaoru@kaisei.org
COMMENT=	Perl implementation of the NULL encryption algorithm

PERL_CONFIGURE=	yes

MAN3=	Crypt::NULL.3

.include <bsd.port.mk>
