# New ports collection makefile for:	peace
# Date created:				30 Jul 2001
# Whom:			TAKAHASHI Kaoru <kaoru@kaisei.org>
#
# $FreeBSD$
#

PORTNAME=	peace
PORTVERSION=	2000.12.21
CATEGORIES=	emulator
MASTER_SITES=	http://www.planet.sci.kobe-u.ac.jp/~takawata/peace/
DISTNAME=       peace4fbsd-kmodule

MAINTAINER=	kaoru@kaisei.org

.include <bsd.port.mk>
